name: DEPLOY ALI ECS

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node v12.x
        uses: actions/setup-node@v1
        with: 
          node-version: "12.x"
      
      - name: Npm install
        run: |
          pwd
          npm install
          npm run build
        env: 
          CI: true

      - name: Deploy Aliyun
        uses: appleboy/scp-action@master
        with: 
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "/dist"
          target: "/usr/local/nginx/html/"